# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69bd45679a61042cb52932cb6d87f804e0865aa02c70d7cba5148480a1031bf93210000537eab57e450b23ec3db065ae6cd23d1c3357676a18e3ee61732f18f7

test:
  secret_key_base: 4481d4ff3a93bb403fed19a74c21d0929faeaf6e33e6ffab998298465dadb497bbf513a65597e2f714579188b4b178b57a5a2a0c3a4b1a98f9095dac0b50fee1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
